### 投稿記事が存在する場合（200 OK）
@post_id = 28443eec-b223-4b14-828f-2b927f037158
GET http://localhost:3000/api/posts/{{post_id}}
Accept: application/json

### 投稿記事が存在しない場合（404）
GET http://localhost:3000/api/posts/0000-0000-0000
Accept: application/json
